# Generated by Django 4.0.1 on 2022-04-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('CHATBOT', 'ChatBot'), ('WEB', 'Web'), ('APP', 'App')], default='WEB', max_length=15)),
                ('contents', models.JSONField()),
                ('relevance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ADDED', 'Added'), ('DISCARDED', 'Discarded')], default='NEW', max_length=14)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ph_signal',
            },
        ),
        migrations.CreateModel(
            name='SignalKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('weight', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'ph_signal_keys',
            },
        ),
    ]
