# Generated by Django 4.0.1 on 2022-08-30 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_source', models.CharField(choices=[('ORIGINAL', 'Original'), ('SECOND_HAND', 'Second-Hand')], default='SECOND_HAND', max_length=15)),
                ('contact_data', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'ph_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('DISCARED', 'Discarded'), ('PROGRESS', 'On Progress'), ('COMPLETE', 'Complete')], default='NEW', max_length=14)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_prof', models.CharField(choices=[('CHW', 'Community Health Worker'), ('LFO', 'Livestock Field Officer'), ('HW', 'Health Worker')], default='HW', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=50, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'ph_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ph_forms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('p_id', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'ph_location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'ph_sector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('TWITTER', 'Twitter'), ('WEB', 'Web'), ('APP', 'App')], default='WEB', max_length=15)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('contents', models.JSONField()),
                ('relevance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ADDED', 'Added'), ('DISCARDED', 'Discarded')], default='NEW', max_length=14)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ph_signal',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.form')),
            ],
            options={
                'verbose_name_plural': 'Stages',
                'db_table': 'ph_stage',
            },
        ),
        migrations.CreateModel(
            name='workflow_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.event')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stage', to='ems.stage')),
            ],
            options={
                'verbose_name_plural': 'Workflow Data',
                'db_table': 'ph_workflow_data',
            },
        ),
        migrations.CreateModel(
            name='workflow_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('cur_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cur_stage', to='ems.stage')),
                ('next_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_stage', to='ems.stage')),
            ],
            options={
                'verbose_name_plural': 'Workflow Config',
                'db_table': 'ph_workflow_cfg',
            },
        ),
        migrations.CreateModel(
            name='SignalKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('weight', models.SmallIntegerField(default=1)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.sector')),
            ],
            options={
                'verbose_name_plural': 'SignalKeys',
                'db_table': 'ph_signal_keys',
            },
        ),
        migrations.CreateModel(
            name='perms_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Perms',
                'db_table': 'ph_perms_users',
            },
        ),
        migrations.CreateModel(
            name='perms_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name_plural': 'Group Perms',
                'db_table': 'ph_perms_group',
            },
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'db_table': 'ph_notes',
            },
        ),
        migrations.CreateModel(
            name='Form_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('col_name', models.CharField(max_length=50)),
                ('col_type', models.CharField(choices=[('DATE', 'Date'), ('BARCODE', 'Barcode'), ('INT', 'Numeric'), ('GEOPOINT', 'Geopoint'), ('TEXT', 'String'), ('INT', 'int'), ('SELECT1', 'Select1'), ('SELECT', 'Select'), ('BINARY', 'Binary'), ('TIME', 'Time'), ('DATETIME', 'DateTime')], default='TEXT', max_length=10)),
                ('options', models.TextField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, null=True)),
                ('label', models.TextField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('required', models.CharField(default=0, max_length=1)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('page', models.IntegerField(blank=True, default=0, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.form')),
            ],
            options={
                'db_table': 'ph_forms_cfgf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('obj', models.FileField(upload_to='assets/library')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'ph_files',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ems.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='sector',
            field=models.ManyToManyField(to='ems.Sector'),
        ),
        migrations.AddField(
            model_name='event',
            name='signal',
            field=models.ManyToManyField(to='ems.Signal'),
        ),
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ems.stage'),
        ),
    ]
