# Generated by Django 4.0.1 on 2022-04-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('weight', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'ph_signal_keys',
            },
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={},
        ),
    ]
