# Generated by Django 4.0.1 on 2022-08-30 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_contact_contact_type_event_title'),
    ]

    operations = [
    ]
