# Generated by Django 4.0.1 on 2022-04-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_signalkeys_alter_signal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='relevance',
            field=models.IntegerField(default=0),
        ),
    ]
