# Generated by Django 4.0.1 on 2022-04-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_sector_signal_contact_perms_user_perms_group_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalkeys',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ems.sector'),
            preserve_default=False,
        ),
    ]
