# Generated by Django 4.0.1 on 2022-04-27 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_signalkeys_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Stages',
                'db_table': 'ph_stage',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CANCELLED', 'Cancelled'), ('PROGRESS', 'On Progress'), ('COMPLETE', 'Complete')], default='NEW', max_length=14),
        ),
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ems.stage'),
            preserve_default=False,
        ),
    ]
