# Generated by Django 4.0.1 on 2022-04-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0006_stage_event_created_on_alter_event_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('contact_source', models.CharField(choices=[('ORIGINAL', 'Original'), ('SECOND_HAND', 'Second-Hand')], default='SECOND_HAND', max_length=15)),
                ('contact_type', models.CharField(choices=[('PHONE', 'Phone Number'), ('ADDRESS', 'Address'), ('EMAIL', 'E-mail')], default='PHONE', max_length=15)),
                ('contact_data', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'db_table': 'ph_contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'ph_location',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.ManyToManyField(to='ems.contact'),
        ),
    ]
