# Generated by Django 4.0.1 on 2022-04-27 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0007_contact_location_event_description_event_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalkeys',
            options={'verbose_name_plural': 'SignalKeys'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('ADDRESS', 'Address'), ('PHONE', 'Phone Number')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ems.location'),
        ),
    ]
