# Generated by Django 4.0.1 on 2022-04-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0008_alter_signalkeys_options_alter_contact_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ManyToManyField(to='ems.Contact'),
        ),
    ]
