# Generated by Django 4.0.1 on 2022-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0009_location_code_alter_event_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
