# Generated by Django 4.0.1 on 2022-04-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_alter_location_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='p_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('PHONE', 'Phone Number'), ('EMAIL', 'E-mail'), ('ADDRESS', 'Address')], default='PHONE', max_length=15),
        ),
    ]
