# Generated by Django 4.0.1 on 2022-04-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0011_location_p_id_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('PHONE', 'Phone Number'), ('EMAIL', 'E-mail')], default='PHONE', max_length=15),
        ),
    ]
