# Generated by Django 4.0.1 on 2022-04-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0012_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('EMAIL', 'E-mail'), ('PHONE', 'Phone Number')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='p_id',
            field=models.CharField(max_length=5),
        ),
    ]
