# Generated by Django 4.0.1 on 2022-04-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0013_alter_contact_contact_type_alter_location_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('ADDRESS', 'Address'), ('PHONE', 'Phone Number')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='p_id',
            field=models.CharField(max_length=25),
        ),
    ]
