# Generated by Django 4.0.1 on 2022-05-11 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0014_alter_contact_contact_type_alter_location_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='contact',
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(default=787878787, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='contact_prof',
            field=models.CharField(choices=[('CHW', 'Community Health Worker'), ('LFO', 'Livestock Field Officer'), ('HW', 'Health Worker')], default='HW', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('EMAIL', 'E-mail'), ('PHONE', 'Phone Number')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='signal',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('TELEGRAM', 'Telegram'), ('TWITTER', 'Twitter'), ('WEB', 'Web'), ('APP', 'App')], default='WEB', max_length=15),
        ),
        migrations.AlterField(
            model_name='signalkeys',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ems.sector'),
        ),
    ]
