# Generated by Django 4.0.1 on 2022-05-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0015_remove_event_contact_event_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('PHONE', 'Phone Number'), ('EMAIL', 'E-mail')], default='PHONE', max_length=15),
        ),
    ]
