# Generated by Django 4.0.1 on 2022-05-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0016_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('EMAIL', 'E-mail'), ('PHONE', 'Phone Number'), ('ADDRESS', 'Address')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ems.stage'),
        ),
    ]
