# Generated by Django 4.0.1 on 2022-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0018_alter_contact_contact_type_alter_event_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('PHONE', 'Phone Number'), ('ADDRESS', 'Address'), ('EMAIL', 'E-mail')], default='PHONE', max_length=15),
        ),
    ]
