# Generated by Django 4.0.1 on 2022-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0019_event_title_alter_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('ADDRESS', 'Address'), ('EMAIL', 'E-mail'), ('PHONE', 'Phone Number')], default='PHONE', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('DISCARED', 'Discarded'), ('PROGRESS', 'On Progress'), ('COMPLETE', 'Complete')], default='NEW', max_length=14),
        ),
    ]
