# Generated by Django 4.0.1 on 2022-04-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulink',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='menulink',
            old_name='sub_menu_id',
            new_name='sub_menu',
        ),
        migrations.RenameField(
            model_name='submenu',
            old_name='menu_id',
            new_name='menu',
        ),
    ]
