# Generated by Django 4.0.1 on 2022-04-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_menu_id_menulink_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='sub_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.submenu'),
        ),
    ]
