# Generated by Django 4.0.1 on 2022-04-06 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_menulink_sub_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message_id', models.CharField(blank=True, max_length=25, null=True)),
                ('channel', models.CharField(default='whatsapp', max_length=25)),
                ('values', models.TextField()),
                ('active', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.menu')),
            ],
            options={
                'verbose_name_plural': 'Menu Sessions',
                'db_table': 'cb_menu_sessions',
            },
        ),
    ]
