# Generated by Django 4.0.1 on 2022-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_menusession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusession',
            name='values',
            field=models.TextField(blank=True, null=True),
        ),
    ]
