# Generated by Django 4.0.1 on 2022-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_alter_menusession_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='sequence',
            field=models.CharField(max_length=10),
        ),
    ]
