# Generated by Django 4.0.1 on 2022-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_submenu_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusession',
            name='channel',
            field=models.CharField(default='whatsapp', max_length=100),
        ),
        migrations.AlterField(
            model_name='menusession',
            name='message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menusession',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
