# Generated by Django 4.0.1 on 2022-04-05 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_sub_token_activation_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sub_token',
        ),
    ]
