# Generated by Django 4.0.1 on 2022-04-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_organization_activation_otp'),
        ('account', '0004_alter_profile_organization'),
    ]

    operations = [
    ]
