# Generated by Django 4.0.1 on 2022-08-30 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credibility_score', models.FloatField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ems.location')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verifier',
                'verbose_name_plural': 'Verifiers',
                'db_table': 'ph_verifiers',
                'managed': True,
            },
        ),
    ]
